import subprocess
import shutil

import pytest

from portscanner.transports._x509_lite import parse_certificate_fields
from portscanner.transports.tcp import _extract_cert_summary

_HAS_OPENSSL = shutil.which("openssl") is not None


def _generate_self_signed_der(cn: str = "hss01.internal.test", org: str = "TestTelecom") -> bytes:
    """Generates a real self-signed certificate with openssl and returns
    the raw DER bytes — a test against a real certificate, not
    manually fabricated data."""
    result = subprocess.run(
        [
            "openssl", "req", "-x509", "-newkey", "rsa:2048", "-keyout", "/dev/null",
            "-out", "-", "-days", "1", "-nodes", "-outform", "DER",
            "-subj", f"/CN={cn}/O={org}",
        ],
        capture_output=True, check=True,
    )
    return result.stdout


@pytest.mark.skipif(not _HAS_OPENSSL, reason="openssl CLI is not available in this environment")
def test_parse_certificate_fields_real_certificate():
    der = _generate_self_signed_der(cn="hss01.internal.test", org="TestTelecom")
    fields = parse_certificate_fields(der)
    assert fields is not None
    assert "hss01.internal.test" in fields["subject"]
    assert "TestTelecom" in fields["subject"]
    # self-signed: subject and issuer are the same
    assert "hss01.internal.test" in fields["issuer"]
    assert fields["not_before"]
    assert fields["not_after"]


def test_parse_certificate_fields_rejects_garbage():
    assert parse_certificate_fields(b"\x00\x01\x02not-a-real-certificate") is None


def test_parse_certificate_fields_rejects_empty():
    assert parse_certificate_fields(b"") is None


class _FakeSSLObject:
    """A mock ssl.SSLObject with no actual network connection, to test
    _extract_cert_summary in isolation — uses a real DER generated by
    openssl if available."""

    def __init__(self, der: bytes | None, version: str = "TLSv1.3", cipher: str = "TLS_AES_256_GCM_SHA384"):
        self._der = der
        self._version = version
        self._cipher = cipher

    def getpeercert(self, binary_form: bool = False):
        if binary_form:
            return self._der
        return {}  # this is actually the real ssl behavior with CERT_NONE — we deliberately mimic it

    def version(self):
        return self._version

    def cipher(self):
        return (self._cipher, "TLSv1.3", 256)


def test_extract_cert_summary_none_when_no_ssl_object():
    assert _extract_cert_summary(None) is None


def test_extract_cert_summary_none_when_no_der_bytes():
    assert _extract_cert_summary(_FakeSSLObject(der=None)) is None


@pytest.mark.skipif(not _HAS_OPENSSL, reason="openssl CLI is not available in this environment")
def test_extract_cert_summary_full_pipeline_with_real_certificate():
    der = _generate_self_signed_der(cn="pcrf02.internal.test", org="AcmeTelecom")
    summary = _extract_cert_summary(_FakeSSLObject(der=der))
    assert summary is not None
    assert "pcrf02.internal.test" in summary["subject"]
    assert "AcmeTelecom" in summary["subject"]
    assert summary["tls_version"] == "TLSv1.3"
    assert summary["cipher"] == "TLS_AES_256_GCM_SHA384"
